### PR TITLE
37 pwa add manifest

### PR DESCRIPTION
**Pull request by CarelS072**
note: linked and added css file to home page as I was adding files for PWA

Documentation done, we will still need to change the icons and colours to something more appropriate

### CODE REVIEW

**Review by chrislaupama — CHANGES_REQUESTED** [review]
Maybe change the font that’s being used to the font in the current design guide instead of Trebuchet MS etc?

**Comment by CarelS072** [comment]
closes #37 

Changed fonts in css an background in screen

**Comment by CarelS072** [comment]
DON"T MERGE looks like my App component did not update when I pulled development

**Comment by CarelS072** [comment]
Should be all good now , please check

**Review by danielle-baek — APPROVED** [review]
Good job Carl! I don't understand everything but it doesn't make error so it seems okay. I'll trust you :D

**Review by chrislaupama — APPROVED** [review]

**Pull request merged**
